2025-02-25 14:37:58,233 - instabot version: 0.117.0 (bot) - INFO - Instabot version: 0.117.0 Started
2025-02-25 14:37:58,233 - instabot version: 0.117.0 (bot) - DEBUG - Bot imported from /home/nill/.local/lib/python3.12/site-packages/instabot/bot/bot.py
2025-02-25 14:37:58,234 - instabot version: 0.117.0 (api_login) - INFO - Not yet logged in starting: PRE-LOGIN FLOW!
2025-02-25 14:37:58,431 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/get_prefill_candidates/ returned response: <Response [200]>
2025-02-25 14:37:58,631 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: qe/sync/ returned response: <Response [200]>
2025-02-25 14:37:58,912 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: launcher/sync/ returned response: <Response [200]>
2025-02-25 14:37:59,079 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/contact_point_prefill/ returned response: <Response [429]>
2025-02-25 14:37:59,079 - instabot version: 0.117.0 (api) - DEBUG - Responsecode indicates error; response content: b'{"message":"Please wait a few minutes before you try again.","status":"fail"}'
2025-02-25 14:37:59,079 - instabot version: 0.117.0 (api) - ERROR - Request returns 429 error!
2025-02-25 14:37:59,079 - instabot version: 0.117.0 (api) - WARNING - That means 'too many requests'. I'll go to sleep for 5 minutes.
2025-02-25 14:42:59,240 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/contact_point_prefill/ returned response: <Response [429]>
2025-02-25 14:42:59,240 - instabot version: 0.117.0 (api) - DEBUG - Responsecode indicates error; response content: b'{"message":"Please wait a few minutes before you try again.","status":"fail"}'
2025-02-25 14:42:59,240 - instabot version: 0.117.0 (api) - ERROR - Request returns 429 error!
2025-02-25 14:42:59,241 - instabot version: 0.117.0 (api) - WARNING - That means 'too many requests'. I'll go to sleep for 10 minutes.
2025-02-25 14:52:59,936 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/contact_point_prefill/ returned response: <Response [429]>
2025-02-25 14:52:59,936 - instabot version: 0.117.0 (api) - DEBUG - Responsecode indicates error; response content: b'{"message":"Please wait a few minutes before you try again.","status":"fail"}'
2025-02-25 14:52:59,936 - instabot version: 0.117.0 (api) - ERROR - Request returns 429 error!
2025-02-25 14:52:59,936 - instabot version: 0.117.0 (api) - WARNING - That means 'too many requests'. I'll go to sleep for 15 minutes.
2025-02-25 15:08:00,130 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/contact_point_prefill/ returned response: <Response [429]>
2025-02-25 15:08:00,130 - instabot version: 0.117.0 (api) - DEBUG - Responsecode indicates error; response content: b'{"message":"Please wait a few minutes before you try again.","status":"fail"}'
2025-02-25 15:08:00,130 - instabot version: 0.117.0 (api) - ERROR - Request returns 429 error!
2025-02-25 15:08:01,130 - instabot version: 0.117.0 (api) - ERROR - Since we hit 15 minutes of time outs, we have to restart. Removing session and cookies. Please relogin.
