2025-03-01 15:11:28,097 - instabot version: 0.117.0 (bot) - INFO - Instabot version: 0.117.0 Started
2025-03-01 15:11:28,097 - instabot version: 0.117.0 (bot) - DEBUG - Bot imported from /home/nill/.local/lib/python3.12/site-packages/instabot/bot/bot.py
2025-03-01 15:11:28,098 - instabot version: 0.117.0 (api_login) - INFO - Not yet logged in starting: PRE-LOGIN FLOW!
2025-03-01 15:11:28,399 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/get_prefill_candidates/ returned response: <Response [429]>
2025-03-01 15:11:28,399 - instabot version: 0.117.0 (api) - DEBUG - Responsecode indicates error; response content: b'{"message":"Please wait a few minutes before you try again.","status":"fail"}'
2025-03-01 15:11:28,400 - instabot version: 0.117.0 (api) - ERROR - Request returns 429 error!
2025-03-01 15:11:28,699 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: qe/sync/ returned response: <Response [200]>
2025-03-01 15:11:28,994 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: launcher/sync/ returned response: <Response [200]>
2025-03-01 15:11:29,123 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/contact_point_prefill/ returned response: <Response [429]>
2025-03-01 15:11:29,123 - instabot version: 0.117.0 (api) - DEBUG - Responsecode indicates error; response content: b'{"message":"Please wait a few minutes before you try again.","status":"fail"}'
2025-03-01 15:11:29,123 - instabot version: 0.117.0 (api) - ERROR - Request returns 429 error!
